Main/app/__init__.py
from flask import Flask
import os

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'your-secret-key'

    from .routes import routes
    from .errors import errors, error_handlers
    app.register_blueprint(routes)
    app.register_blueprint(errors)
    error_handlers(app)

    return app

Main/app/routes.py
from flask import Blueprint, render_template

routes = Blueprint('routes', __name__)

@routes.route("/", methods=["GET"])
def home():
    return render_template("routes/home.html")

@routes.route("/documentation", methods=["GET"])
def documentation():
    return render_template("routes/documentation.html")

Main/app/templates/base.html
<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Nagy Gergely Attila, Kiss Miklós, Lilik Levente">
    <meta name="keywords" content="Ourtube">
    <link rel="icon" href="https://i.imgur.com/vSvejyq.png">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/mainstyle.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/home.css') }}">
    <title>Ourtube</title>
</head>
<body>
    <header>
        <menu>
            <nav class="navbar">
                <ul class="nav-list">
                      <li>
                        <img src="https://i.imgur.com/vSvejyq.png" id="loGlobalOffensive">
                    </li>
                    <li>
                        <a href="{{ url_for('routes.home') }}">Home</a>
                    </li>
                </ul>
            </nav>
        </menu>
    </header>

    <main>
        {% block body %}{% endblock %}
    </main>

    <footer>
        {% block footer %}{% endblock %}
        <div class="footer">
            <p>Copyright© 2025 OurTube. All rights reserved.</p>
        </div>
    </footer>
    
</body>
</html>

Main/app/templates/routes/documentation.html
{% extends "base.html" %}


{% block header %}{% endblock %}

{% block body %}
    <div>
        <iframe src="{{ url_for('static', filename='documentation/documentation.pdf') }}" frameborder="0"></iframe>
    </div>
{% endblock %}

{% block footer %}{% endblock %}  

Main/app/templates/routes/home.html
{% extends "base.html" %}


{% block header %}{% endblock %}

{% block body %}
    <div class="container">
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/egy.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/kettő.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/három.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/négy.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/öt.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/hat.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/hét.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/nyolc.mp4') }}" type="video/mp4">
            </video>
        </div>
        <div class="child">
            <video width="100%" height="100%" controls>
                <source src="{{ url_for('static', filename='videos/kilenc.mp4') }}" type="video/mp4">
            </video>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}  